/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FooterApp: typeof import('./src/components/FooterApp.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HeaderApp: typeof import('./src/components/HeaderApp.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Workdialog: typeof import('./src/components/Workdialog.vue')['default']
  }
}
